onBudget/urls.py
"""
This file is in charge of managing the app routes that we want access to .
this is the principal fileas this file is needed in every app
"""
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('budget/', include('appBudget.urls')),
    path('admin/', admin.site.urls),
]

appBudget/models.py
from django.contrib.auth.models import User
from django.db import models

"""
This model manages a category namer based on their name and description
Attributes: "max_length" = to define the maximum number of chars that the field can have
Atributes: "verbose_name" = to define the name with which it will be displayed  

"""
class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Name')
    description = models.TextField(max_length=500, verbose_name='Description')

    def __str__(self):
        return self.name


"""
This model manages the budget plans of a user in a range of dates
Attributes: "on_delete" = To define the behavior of the foreign key when a planning is deleted. 
Atributes: "default" = To define the default value this field must have in case of being empty. 
"""
class Planning(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name='User')  # Cascade: if the parent is deleted the child is deleted
    budget = models.FloatField(default=0, verbose_name='Budget')
    date_start = models.DateField(verbose_name='Start date')
    date_end = models.DateField(verbose_name='End date')

    def __str__(self):  # To create a custom print behavior
        return '%s - %s' % (self.user, self.budget)  # user y budget


"""
This model manages the budget plannings of a user for all the categories belonging to a planning. Home › Appbudget › Category plannings › 10.0 - Home Expenses. 
Si quiero editar un valor que estaba inputed en una categoria. 
"""
class CategoryPlanning(models.Model):
    budget = models.FloatField(default=0, verbose_name='Budget')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Category')
    planning = models.ForeignKey(Planning, on_delete=models.CASCADE, verbose_name='Planning')

    def __str__(self):
        return '%s - %s' % (self.budget, self.category)


"""
This model managaes the corresponding expenses to a specific budget in the category plannings.

"""
class PlanningExpenses(models.Model):
    amount = models.FloatField(default=0, verbose_name='Amount')
    category_planning = models.ForeignKey(CategoryPlanning, on_delete=models.CASCADE, verbose_name='Category Planning')
    date = models.DateField(verbose_name='Date')
    description = models.TextField(max_length=500, verbose_name='Description')

    def __str__(self):
        return '%s - %s - %s' % (self.category_planning.category, self.amount, self.date)
        # %s reemplazo de variables la s indica que son de tipo string (seran reemplazadas por self.category_planning.category, self.amount, self.date

templates/add_category_planning.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
        <div class="container">
            <h1 class="display-5">Add category planning!</h1>
        </div>
    </div>

    <div class="container">

        <div class="row">
            <div class="col">
                <h3>
                    {{ planning.user }} - {{ planning.budget|floatformat:2 }}
                    <span style="font-size: 50%">({{ planning.date_start|date:"SHORT_DATE_FORMAT" }} - {{ planning.date_end|date:"SHORT_DATE_FORMAT" }})</span>
                </h3>
            </div>
        </div>

        <hr>

        <form action="{% url 'add_category_planning' planning.pk %}" method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for form in formset %}
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.id_for_label }}">Category:</label>
                            {{ form.category }}
                        </div>

                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.id_for_label }}">Budget:</label>
                            {{ form.budget }}
                        </div>
                    </div>
                </div>
            {% endfor %}

            <div class="row">
                <dic class="col text-right">
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                    <button type="submit" class="btn btn-primary">Finish</button>
                </dic>
            </div>
        </form>

    </div>
{% endblock content %}

templates/add_planning.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
        <div class="container">
            <h1 class="display-5">Add planning!</h1>
        </div>
    </div>

    <div class="container">
        <form action="{% url 'add_planning' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="{{ form.user.id_for_label }}">User:</label>
                        {{ form.user }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="{{ form.budget.id_for_label }}">Budget:</label>
                        {{ form.budget }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="{{ form.date_start.id_for_label }}">Start date:</label>
                        {{ form.date_start }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="{{ form.date_end.id_for_label }}">Finish date:</label>
                        {{ form.date_end }}
                    </div>
                </div>
            </div>

            <div class="row">
                <dic class="col text-right">
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                    <button type="submit" class="btn btn-primary">Continue</button>
                </dic>
            </div>

        </form>
    </div>
{% endblock content %}

templates/add_planning_expenses.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
        <div class="container">
            <h1 class="display-5">Add planning expenses!</h1>
        </div>
    </div>

    <div class="container">
        <form action="{% url 'add_planning_expenses' plan.pk plan.user.username %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="{{ form.category_planning.id_for_label }}">Planning category:</label>
                        {{ form.category_planning }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="{{ form.amount.id_for_label }}">Amount:</label>
                        {{ form.amount }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="{{ form.date.id_for_label }}">Date:</label>
                        {{ form.date }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="{{ form.description.id_for_label }}">Description:</label>
                        {{ form.description }}
                    </div>
                </div>
            </div>

            <div class="row">
                <dic class="col text-right">
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                    <button type="submit" class="btn btn-primary">Continue</button>
                </dic>
            </div>

        </form>
    </div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>onBudget planning!</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <style>
        body {
            padding-top: 3.5rem;
        }
    </style>
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">OnBudget</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'list_planning' %}">
                    <i class="fa fa-list"></i>
                    <span>Planning list</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block content %}
{% endblock content %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>


</body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}
    <main role="main">

        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
            <div class="container">
                <h1 class="display-3">ON$BUDGET</h1>
                <p>Here's to the NEW SPENDERS, The Z GENERATION, The REBELS, The TROUBLEMAKERS, THE MILLENIALS </p>
                <p>TAKE CONTROL OF YOUR BUDGET!!</p>
                <p><a class="btn btn-primary btn-lg" href="{% url 'add_planning' %}" role="button">Add a new planning <i
                        class="fa fa-plus"></i></a></p>
            </div>
        </div>

        <div class="container">
            <!-- Example row of columns -->
            <div class="row">
                {% for planning in planning_list %}
                    <div class="col-md-4">
                        <h2><i class="fa fa-calendar-alt"></i> Planning ({{ forloop.counter }})</h2>
                        <p>
                            This planning belongs to {{ planning.user.get_full_name }} and has a budget of
                            ${{ planning.budget|floatformat:2 }}
                            for the period between {{ planning.date_start|date:"SHORT_DATE_FORMAT" }}
                            and {{ planning.date_end|date:"SHORT_DATE_FORMAT" }}.
                        </p>
                        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
                    </div>
                {% endfor %}
            </div>

            <hr>

        </div> <!-- /container -->

    </main>
{% endblock content %}

templates/list_planning.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
        <div class="container">
            <h1 class="display-5">Planning list!</h1>
        </div>
    </div>

    <div class="container">
        <div class="table-responsive">
            <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">User</th>
                <th scope="col">Budget</th>
                <th scope="col">Start date</th>
                <th scope="col">End date</th>
                <th scope="col" width="20%">Categories</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for plan in plannings %}
                <tr>
                    <th scope="row">{{ plan.user.get_full_name }}</th>
                    <td>{{ plan.budget|floatformat:2 }}</td>
                    <td>{{ plan.date_start|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ plan.date_end|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>
                        {% for cp in plan.categoryplanning_set.all %}
                            <span class="badge badge-secondary">{{ cp.category.name }} - {{ cp.budget|floatformat:2 }}</span>
                        {% endfor %}
                    </td>
                    <td>
                        <a href="{% url 'planning_expenses' plan.pk plan.user.username %}"
                           class="btn btn-outline-primary btn-sm"
                           data-toggle="tooltip" data-placement="top"
                           title="See expenses"><i
                                class="fa fa-eye"></i></a>
                        <a href="{% url 'add_planning_expenses' plan.pk plan.user.username %}"
                           class="btn btn-outline-primary btn-sm"
                           data-toggle="tooltip" data-placement="top"
                           title="Add expenses"><i class="fa fa-coins"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endblock content %}

templates/planning_expenses.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
        <div class="container">
            <h1 class="display-5">Planning expenses for <em>{{ user.get_full_name }}</em></h1>
        </div>
    </div>

    <div class="container">

        <div class="row">
            <div class="col-sm">
                <a href="{% url 'list_planning' %}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Back</a>
            </div>
        </div>

        <div style="margin: 30px auto"></div>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Planning category</th>
                    <th scope="col">Date</th>
                    <th scope="col">Description</th>
                    <th scope="col">Amount</th>
                </tr>
                </thead>
                <tbody>
                {% for pe in planning_expenses %}
                    <tr>
                        <td scope="row"><span class="badge badge-secondary">{{ pe.category_planning }}</span></td>
                        <td>{{ pe.date|date:"SHORT_DATE_FORMAT" }}</td>
                        <td>{{ pe.description }}</td>
                        <td>{{ pe.amount|floatformat:2 }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}